// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "assistant",
    columns: [{ name: "assistantId", type: "string", unique: true }],
  },
  {
    name: "userThread",
    columns: [
      { name: "userId", type: "string", unique: true },
      { name: "threadId", type: "string", unique: true },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Assistant = InferredTypes["assistant"];
export type AssistantRecord = Assistant & XataRecord;

export type UserThread = InferredTypes["userThread"];
export type UserThreadRecord = UserThread & XataRecord;

export type DatabaseSchema = {
  assistant: AssistantRecord;
  userThread: UserThreadRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Kazu-s-workspace-dpbfr7.eu-central-1.xata.sh/db/goggins-ai-coach",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
